### ISSUE TITLE
Copy-pasting into portable text field throws error after upgrading from 2.30.5 to 2.33.3

### ISSUE THREAD

**Issue by AnnaMichaelsen** [sanity-io/sanity#3685]
**Describe the bug**
After upgrading the studio from 2.30.5 to 2.33.3 there seems to be a bug with copy-pasting into a portable text field. Whenever pasting something, the copied text is not pasted, and the error `undefined is not a function` is thrown. Never had an issue with this in previous studio versions. Happens with whichever type of text, including plain text.

**To Reproduce**

1. Install studio v2.33.3
2. Copy-paste something into a portable text field

**Expected behavior**
Copy-pasting without any issues.

**Screenshots**
<img width="866" alt="Screenshot 2022-09-25 at 10 38 46" src="https://user-images.githubusercontent.com/45261817/192365976-94d0bbaa-3d19-46c4-ad5f-310f2d08e48f.png">
<img width="1792" alt="Screenshot 2022-09-25 at 10 39 55" src="https://user-images.githubusercontent.com/45261817/192366024-2f4a3f68-3389-4ce6-b678-65a197b9d5c1.png">

**Which versions of Sanity are you using?**
2.33.3

**Comment by eivindml** [comment]
This is still happening for me. :( For many clients, it's important to be able to copy-paste the content.

**Comment by lampa-da** [comment]
I have the same issue. I hope it is going to be fixed soon.

![Screenshot 2022-12-03 at 8 44 06 PM](https://user-images.githubusercontent.com/20567421/205474916-bf13430d-78c2-4e90-95f5-0266e3015f35.png)
**Which versions of Sanity are you using?**
2.29.8

**Comment by kexhest** [comment]
Could this issue be related to this commit? https://github.com/sanity-io/sanity/commit/8644e1156c7d3a6cf91277cee9d6a1e92784fc37

It seems like v2 uses the v3 portable text editor?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
