### ISSUE TITLE
[v3] Paste text in a field type block leads to error

### ISSUE THREAD

**Issue by raulfdm** [sanity-io/sanity#3552]
**Describe the bug**

After I upgraded to v3, I notice that when I try to paste a text (`cmd + v`) in a type block field, it leads to an error:

Trace in dev:

```
TypeError: undefined is not a function
    at Array.find (<anonymous>)
    at blockContentFeatures (schema.ts:31:35)
    at createRuleOptions (usePortableTextEditorValue.ts:25:20)
    at new HtmlDeserializer (withoutPatching.ts:50:57)
    at htmlToBlocks (array.ts:21:24)
    at editor2.insertTextOrHTMLData (ActivateOnFocus.js:190:26)
    at editor2.insertData (ActivateOnFocus.js:228:16)
    at MemberFieldError.js:289:19
    at isEventHandled (index.ts:1585:37)
    at index.ts:1446:18
```

**To Reproduce**

1. create a project in v3;
2. have a schema type that contains code block type
3. try to paste something
4. see the error

<details>
<summary>My block content field type</summary>

```ts
export const blockContent = {
  title: 'Block Content',
  name: 'blockContent',
  type: 'array',
  of: [
    {
      title: 'Block',
      type: 'block',
      styles: [{title: 'Normal', value: 'normal'}],
      lists: [{title: 'Bullet', value: 'bullet'}],
      marks: {
        decorators: [
          {title: 'Strong', value: 'strong'},
          {title: 'Emphasis', value: 'em'},
        ],
        annotations: [
          {
            title: 'URL',
            name: 'link',
            type: 'object',
            fields: [
              {
                title: 'URL',
                name: 'href',
                type: 'url',
              },
            ],
          },
        ],
      },
    },
  ],
}

```
</details>

**Expected behavior**

I'm able to paste any text in this field

**Screenshots**

https://user-images.githubusercontent.com/12464600/186014557-301ad6f3-dfd6-4392-a31a-80c4dd5fa6dd.mp4

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

```
➜  sales-platform git:(main) ✗ pnpm exec sanity versions     
@sanity/cli  2.28.0 (latest: 2.30.6)
```

But also:

```json
{
"dependencies": {
    "@mdx-js/react": "2.1.3",
    "@sales-platform/core": "workspace:*",
    "@sales-platform/eslint-config": "workspace:*",
    "@sanity/types": "2.30.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-is": "18.2.0",
    "sanity": "3.0.0-dev-preview.15",
    "sanity-plugin-media": "2.0.0-v3-studio.0",
    "styled-components": "5.3.5"
  },
  "devDependencies": {
    "@sanity/eslint-config-studio": "2.0.0",
    "eslint": "8.22.0",
    "prettier": "2.7.1",
    "typescript": "4.7.4"
  },
}
```

**What operating system are you using?**

```
Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
```

**Which versions of Node.js / npm are you running?**

```
    Binaries:
      Node: 16.16.0
      npm: 7.24.2
      Yarn: 1.22.17
      pnpm: 7.8.0
```

**Additional context**

This problem only appears in v3.

I was using React 17, I tried to migrated to 18, same error.

**Security issue?**

No

**Comment by rexxars** [comment]
Duplicate of #3532 - thanks for reporting
